INSERT INTO localities (name, country) VALUES
        ('South Dakota', 'USA'), 
        ('British Isles', 'England'), 
        ('Southwest USA', 'USA'), 
        ('Upper Peninsula', 'USA'), 
        ('Andes Mountains', 'Chile'), 
        ('Australia', 'Australia'), 
        ('Amazon Rainforest', 'Brazil'), 
        ('Southern Africa', 'South Africa'), 
        ('Western United States', 'USA'),
        ('Mediterranean Region', 'Cyprus'),
        ('Great Salt Lake', 'USA'),
        ('Himalayas', 'India'),
        ('Maritimes', 'Canada'),
        ('Pyrenees Mountains', 'France'), 
        ('Greek Islands', 'Greece'), 
        ('North Africa', 'Morocco'), 
        ('Permian Basin', 'USA'), 
        ('Black Forest', 'Germany'), 
        ('Yunnan Province', 'China'), 
        ('Okavango Delta', 'Botswana'),
        ('Ural Mountains', 'Russia'), 
        ('Hardangervidda', 'Norway'), 
        ('Patagonia', 'Argentina'), 
        ('Faroe Islands', 'Faroe');